import { beforeEach, describe, expect, it, vi } from 'vitest'
import { apiClient } from './apiClient'
import { getClassWeeklyLessonLogs, getLessonLogPolicy, getMyLessonSchedule, listLessonLogClasses, listLessonLogRevisions, recordLateLessonLog, reviewLessonLog, updateLessonLog, updateLessonLogPolicy, amendLessonLog, signWeeklyReview } from './lessonLogApi'

vi.mock('./apiClient', () => ({ apiClient: { get: vi.fn(), put: vi.fn(), post: vi.fn() } }))
describe('lessonLogApi', () => {
  beforeEach(() => vi.clearAllMocks())
  it('maps the published schedule item and its nested persisted entry', async () => { vi.mocked(apiClient.get).mockResolvedValue({ date: '2026-09-14', timezone: 'Asia/Ho_Chi_Minh', items: [{ entryId: 3, timetableEntryId: 9, timetableRevisionId: 4, assignmentId: 5, classId: 7, subjectId: 8, assignedTeacherId: 2, semesterId: 1, className: '10A1', subjectName: 'Toán', teacherName: 'Cô A', functionalRoomName: null, lessonDate: '2026-09-14', session: 'MORNING', periodIndex: 1, lessonEndsAt: '2026-09-14T02:00:00', editWindowExpiresAt: '2026-09-16T02:00:00', status: 'SUBMITTED', version: 4, policyId: 1, rosterCountSnapshot: 40, canCreate: false, canLateRecord: true, blockedReason: null, entry: { entryId: 3, timetableEntryId: 9, classId: 7, semesterId: 1, lessonDate: '2026-09-14', session: 'MORNING', periodIndex: 1, status: 'SUBMITTED', version: 4, title: 'Hàm số' } }] }); const result = await getMyLessonSchedule('2026-09-14', 't'); expect(result.items[0]?.entry?.entryId).toBe(3); expect(result.items[0]?.subjectName).toBe('Toán'); expect(result.items[0]?.canCreate).toBe(false); expect(result.items[0]?.canLateRecord).toBe(true); expect(apiClient.get).toHaveBeenCalledWith('/api/v3/lesson-logs/my-schedule', { token: 't', query: { date: '2026-09-14' } }) })
  it('uses ResultPaginationDTO result and zero-based query', async () => { vi.mocked(apiClient.get).mockResolvedValue({ result: [], meta: { page: 0, pageSize: 20, totalPages: 0, totalItems: 0 } }); await listLessonLogRevisions(9, 0, 20); expect(apiClient.get).toHaveBeenCalledWith('/api/v3/lesson-logs/entries/9/revisions', { token: undefined, query: { page: 0, pageSize: 20 } }) })
  it('sends expectedVersion for optimistic updates', async () => { vi.mocked(apiClient.put).mockResolvedValue({}); await updateLessonLog(7, { expectedVersion: 3, title: 'Bài mới' }); expect(apiClient.put).toHaveBeenCalledWith('/api/v3/lesson-logs/entries/7', { expectedVersion: 3, title: 'Bài mới' }, { token: undefined }) })
  it('maps the backend JSON rubric into the typed policy model', async () => { vi.mocked(apiClient.get).mockResolvedValue({ policyId: 1, policyVersion: 2, version: 4, effectiveFrom: '2026-10-01', timezone: 'Asia/Ho_Chi_Minh', deadlineMode: 'FIXED_HOURS', editWindowHours: 48, requireHomeroomReview: true, rubric: '[{"code":"A","label":"Tốt","description":"Đạt"}]' }); const result = await getLessonLogPolicy('2026-10-01', 't'); expect(result.rubric[0]?.code).toBe('A'); expect(apiClient.get).toHaveBeenCalledWith('/api/v3/lesson-logs/policy', { token: 't', query: { date: '2026-10-01' } }) })
  it('serializes policy rubric and sends the transition reason field', async () => { vi.mocked(apiClient.put).mockResolvedValue({ rubric: '[]' }); await updateLessonLogPolicy({ expectedVersion: 1, effectiveFrom: '2026-10-01', timezone: 'Asia/Ho_Chi_Minh', deadlineMode: 'FIXED_HOURS', editWindowHours: 48, requireHomeroomReview: true, rubric: [], reason: 'Cập nhật hạn sửa' }, 't'); expect(apiClient.put).toHaveBeenCalledWith('/api/v3/lesson-logs/policy', expect.objectContaining({ rubric: '[]' }), { token: 't' }); vi.mocked(apiClient.post).mockResolvedValue({ entryId: 2, timetableEntryId: 3, classId: 4, semesterId: 1, lessonDate: '2026-09-14', session: 'MORNING', periodIndex: 1, status: 'SUBMITTED', version: 1 }); await reviewLessonLog(2, 1, 'Đã kiểm tra', 'Ổn', 't'); expect(apiClient.post).toHaveBeenCalledWith('/api/v3/lesson-logs/entries/2/review', { expectedVersion: 1, comment: 'Ổn', reason: 'Đã kiểm tra' }, { token: 't' }) })
  it('maps the backend class lookup names to the view model', async () => { vi.mocked(apiClient.get).mockResolvedValue([{ classId: 7, semesterId: 2, classCode: '10A1', className: 'Lớp 10A1' }]); await expect(listLessonLogClasses(2, 't')).resolves.toEqual([{ id: 7, name: 'Lớp 10A1' }]) })
  it('maps server calendar days and current expected entries without reusing a signed snapshot', async () => { vi.mocked(apiClient.get).mockResolvedValue({ classId: 7, semesterId: 2, weekStart: '2026-09-14', weekEnd: '2026-09-20', calendarDays: [{ date: '2026-09-14', label: 'Thứ Hai', kind: 'SCHOOL_DAY' }, { date: '2026-09-15', label: 'Thứ Ba', kind: 'SCHOOL_DAY' }, { date: '2026-09-16', label: 'Thứ Tư', kind: 'HOLIDAY' }], items: [{ entryId: 3, timetableEntryId: 9, classId: 7, semesterId: 2, lessonDate: '2026-09-14', session: 'MORNING', periodIndex: 1, status: 'SUBMITTED', version: 4, grade: 'A', className: null, subjectName: null, teacherName: null, canReview: true, canAmend: false }, { entryId: 0, timetableEntryId: 10, classId: 7, semesterId: 2, lessonDate: '2026-09-15', session: 'AFTERNOON', periodIndex: 2, status: 'UNLOGGED', version: 0, canLateRecord: true, canTeacherEdit: false }], weeklyReview: { reviewId: 5, status: 'SIGNED', version: 2, weeklyComment: 'Ổn', weeklyGrade: 'A', signedBy: 12, expectedEntries: [{ entryId: 3, version: 5 }, { entryId: 10, version: 1 }], blockedReason: null, signedSnapshotJson: '{"entries":[{"entryId":3,"version":4}]}' } }); const result = await getClassWeeklyLessonLogs(7, 2, '2026-09-14', 't'); expect(result.calendarDays).toEqual([{ date: '2026-09-14', label: 'Thứ Hai', kind: 'SCHOOL_DAY' }, { date: '2026-09-15', label: 'Thứ Ba', kind: 'SCHOOL_DAY' }, { date: '2026-09-16', label: 'Thứ Tư', kind: 'HOLIDAY' }]); expect(result.summary.gradeCounts.A).toBe(1); expect(result.summary.unlogged).toBe(1); expect(result.items[0]?.className).toBeNull(); expect(result.items[0]?.canReview).toBe(true); expect(result.weeklyReview?.expectedEntries).toEqual([{ entryId: 3, version: 5 }, { entryId: 10, version: 1 }]); expect(result.weeklyReview?.signedSnapshot).toEqual({ entries: [{ entryId: 3, version: 4 }] }); expect(result.weeklyReview?.signedBy).toBe('12') })
  it('keeps expected entries empty when the backend omits the current token list', async () => { vi.mocked(apiClient.get).mockResolvedValue({ classId: 7, semesterId: 2, weekStart: '2026-09-14', weekEnd: '2026-09-20', calendarDays: [], items: [], weeklyReview: { reviewId: 5, status: 'STALE', version: 2, expectedEntries: undefined, signedSnapshotJson: '{"entries":[{"entryId":3,"version":4}]}' } }); const result = await getClassWeeklyLessonLogs(7, 2, '2026-09-14', 't'); expect(result.weeklyReview?.expectedEntries).toEqual([]); expect(result.weeklyReview?.signedSnapshot).toEqual({ entries: [{ entryId: 3, version: 4 }] }) })
  it('maps raw audit JSON and sends all amended editable fields', async () => { vi.mocked(apiClient.get).mockResolvedValue({ result: [{ revisionId: 8, entryId: 3, action: 'AMEND', actorId: 12, reason: 'Sửa nội dung', beforeStateJson: '{"grade":"B"}', afterStateJson: '{"grade":"A"}', createdAt: '2026-09-15T01:00:00' }], meta: { page: 0, pageSize: 20, totalPages: 1, totalItems: 1 } }); const audit = await listLessonLogRevisions(3, 0, 20, 't'); expect(audit.result[0]?.actorName).toBe('Người dùng #12'); expect(audit.result[0]?.beforeState).toEqual({ grade: 'B' }); vi.mocked(apiClient.post).mockResolvedValue({ entryId: 3, timetableEntryId: 9, classId: 7, semesterId: 2, lessonDate: '2026-09-14', session: 'MORNING', periodIndex: 1, status: 'AMENDED', version: 5 }); const payload = { expectedVersion: 4, reason: 'Sửa nội dung', title: 'Bài mới', completionStatus: 'ON_SCHEDULE' as const, grade: 'A' as const, presentCount: 29, absentCount: 1 }; await amendLessonLog(3, payload, 't'); expect(apiClient.post).toHaveBeenCalledWith('/api/v3/lesson-logs/entries/3/amend', payload, { token: 't' }) })
  it('sends late record fields and required reason to the existing endpoint', async () => { vi.mocked(apiClient.post).mockResolvedValue({ entryId: 10, timetableEntryId: 99, classId: 7, semesterId: 2, lessonDate: '2026-09-15', session: 'AFTERNOON', periodIndex: 2, status: 'AMENDED', version: 1 }); const payload = { timetableEntryId: 99, lessonDate: '2026-09-15', reason: 'Bổ sung sau khi rà soát', title: 'Bài học', completionStatus: 'ON_SCHEDULE' as const, grade: 'A' as const, presentCount: 38, absentCount: 2 }; await expect(recordLateLessonLog(payload, 't')).resolves.toMatchObject({ status: 'AMENDED' }); expect(apiClient.post).toHaveBeenCalledWith('/api/v3/lesson-logs/entries/late-record', payload, { token: 't' }) })
  it('normalizes signed weekly review responses returned by the controller', async () => { vi.mocked(apiClient.post).mockResolvedValue({ reviewId: 5, status: 'SIGNED', version: 3, weeklyComment: 'Đã ký', weeklyGrade: 'B', signedBy: 12, expectedEntries: [{ entryId: 3, version: 6 }], signedSnapshotJson: '{"entries":[{"entryId":3,"version":5}]}' }); await expect(signWeeklyReview(7, { semesterId: 2, weekStart: '2026-09-14', expectedVersion: 2, expectedEntries: [{ entryId: 3, version: 4 }] }, 't')).resolves.toMatchObject({ signedBy: '12', expectedEntries: [{ entryId: 3, version: 6 }] }) })
})
