<script setup lang="ts">
import Button from 'primevue/button'
import Column from 'primevue/column'
import DataTable from 'primevue/datatable'
import StatusTag from '@/components/StatusTag.vue'
import type { ClassSubject, Subject } from '@/types/academic'
import type { SubjectTeachingAssignment } from '@/types/assignment'
import type { Teacher } from '@/types/teacher'
const props = withDefaults(defineProps<{ classSubjects?: ClassSubject[]; subjects?: Subject[]; assignments?: SubjectTeachingAssignment[]; teachers?: Teacher[]; loading?: boolean; readOnly?: boolean }>(), { classSubjects: () => [], subjects: () => [], assignments: () => [], teachers: () => [], loading: false, readOnly: false })
const emit = defineEmits<{ assign: [classSubject: ClassSubject]; replace: [assignment: SubjectTeachingAssignment]; end: [assignment: SubjectTeachingAssignment] }>()
function subjectName(id: number): string { return props.subjects.find((s) => s.id === id)?.name ?? `Môn #${id}` }
function assignment(item: ClassSubject): SubjectTeachingAssignment | undefined { return props.assignments.find((a) => a.classSubjectId === item.id && a.status === 'ACTIVE') }
function teacherName(id?: number): string { if (!id) return 'Chưa phân công'; const t = props.teachers.find((x) => x.id === id); return t ? `${t.teacherCode} - ${t.teacherName}` : `Giáo viên #${id}` }
</script>
<template><section class="content-surface"><div class="section-heading"><div><h2>Phân công giáo viên bộ môn</h2><p class="section-caption">Danh sách môn học của lớp trong học kỳ đã chọn.</p></div></div><div class="table-shell catalog-table"><DataTable :value="props.classSubjects" :loading="props.loading" data-key="id" striped-rows responsive-layout="scroll"><template #empty><div class="empty-state"><i class="pi pi-book" aria-hidden="true" /><strong>Chưa có môn học lớp</strong></div></template><Column header="#"><template #body="slot">{{ slot.index + 1 }}</template></Column><Column header="Môn học"><template #body="slot"><strong>{{ subjectName(slot.data.subjectId) }}</strong></template></Column><Column header="GVBM phụ trách"><template #body="slot">{{ teacherName(assignment(slot.data)?.teacherId) }}</template></Column><Column header="Hiệu lực"><template #body="slot">{{ assignment(slot.data)?.validFrom || '—' }}</template></Column><Column header="Trạng thái"><template #body="slot"><StatusTag :label="assignment(slot.data)?.status || 'Chưa phân công'" :severity="assignment(slot.data) ? 'success' : 'secondary'" /></template></Column><Column header="Thao tác"><template #body="slot"><div class="table-actions"><Button v-if="!assignment(slot.data) && !props.readOnly" icon="pi pi-plus" text rounded aria-label="Phân công giáo viên bộ môn" title="Phân công" @click="emit('assign', slot.data)" /><template v-else-if="assignment(slot.data)"><Button v-if="!props.readOnly" icon="pi pi-sync" text rounded severity="warn" aria-label="Thay giáo viên bộ môn" title="Thay thế" @click="emit('replace', assignment(slot.data)!)" /><Button v-if="!props.readOnly" icon="pi pi-stop" text rounded severity="danger" aria-label="Kết thúc phân công bộ môn" title="Kết thúc" @click="emit('end', assignment(slot.data)!)" /></template></div></template></Column></DataTable></div></section></template>
