<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import Select from 'primevue/select'
import FormAlert from '@/components/FormAlert.vue'
import type { HomeroomAssignment, AssignmentFormValues } from '@/types/assignment'
import type { Teacher } from '@/types/teacher'
const props = withDefaults(defineProps<{ visible?: boolean; mode?: 'create' | 'replace' | 'end'; assignment?: HomeroomAssignment | null; teachers?: Teacher[]; saving?: boolean; errorMessage?: string }>(), { visible: false, mode: 'create', assignment: null, teachers: () => [], saving: false, errorMessage: '' })
const emit = defineEmits<{ 'update:visible': [value: boolean]; save: [values: AssignmentFormValues]; cancel: [] }>()
const values = reactive<AssignmentFormValues>({ mode: 'create', teacherId: null, validFrom: '', validTo: '' })
const errors = reactive<Record<string, string>>({})
const heading = computed(() => props.mode === 'end' ? 'Kết thúc phân công GVCN' : props.mode === 'replace' ? 'Thay đổi GVCN' : 'Phân công GVCN')
watch(() => [props.visible, props.mode, props.assignment], () => { values.mode = props.mode; values.teacherId = null; values.validFrom = props.mode === 'end' ? props.assignment?.validFrom ?? '' : ''; values.validTo = ''; Object.keys(errors).forEach((k) => delete errors[k]) }, { immediate: true, deep: true })
function save(): void { Object.keys(errors).forEach((k) => delete errors[k]); if (props.mode !== 'end' && !values.teacherId) errors.teacherId = 'Giáo viên là bắt buộc.'; if (!values.validFrom) errors.validFrom = 'Ngày bắt đầu là bắt buộc.'; if (props.mode === 'end' && !values.validTo) errors.validTo = 'Ngày kết thúc là bắt buộc.'; if (values.validFrom && values.validTo && values.validTo < values.validFrom) errors.validTo = 'Ngày kết thúc phải sau ngày bắt đầu.'; if (!Object.keys(errors).length) emit('save', { ...values, mode: props.mode }) }
function close(): void { emit('update:visible', false); emit('cancel') }
</script>
<template><Dialog :visible="props.visible" modal :header="heading" :style="{ width: 'min(100% - 2rem, 560px)' }" @update:visible="emit('update:visible', $event)"><FormAlert v-if="props.errorMessage" tone="error" :message="props.errorMessage" /><form class="form-stack" novalidate @submit.prevent="save"><div v-if="props.mode !== 'end'" class="field-group"><label for="homeroom-teacher">Giáo viên *</label><Select id="homeroom-teacher" v-model="values.teacherId" :options="props.teachers.filter((t) => t.status === 'ACTIVE')" option-label="teacherName" option-value="id" placeholder="Chọn giáo viên" :invalid="Boolean(errors.teacherId)" fluid /><small v-if="errors.teacherId" class="field-error">{{ errors.teacherId }}</small></div><div v-if="props.mode !== 'end'" class="field-group"><label for="homeroom-from">Ngày bắt đầu *</label><InputText id="homeroom-from" v-model="values.validFrom" type="date" :invalid="Boolean(errors.validFrom)" fluid /><small v-if="errors.validFrom" class="field-error">{{ errors.validFrom }}</small></div><div v-if="props.mode === 'end'" class="field-group"><label for="homeroom-to">Ngày kết thúc *</label><InputText id="homeroom-to" v-model="values.validTo" type="date" :invalid="Boolean(errors.validTo)" fluid /><small v-if="errors.validTo" class="field-error">{{ errors.validTo }}</small></div><div v-if="props.mode !== 'end'" class="field-group"><label for="homeroom-to-optional">Ngày kết thúc</label><InputText id="homeroom-to-optional" v-model="values.validTo" type="date" :invalid="Boolean(errors.validTo)" fluid /><small v-if="errors.validTo" class="field-error">{{ errors.validTo }}</small></div><div class="form-actions"><Button type="button" label="Hủy" icon="pi pi-times" severity="secondary" outlined :disabled="props.saving" @click="close" /><Button type="submit" :label="props.mode === 'end' ? 'Kết thúc' : props.mode === 'replace' ? 'Xác nhận thay thế' : 'Phân công'" icon="pi pi-check" :loading="props.saving" /></div></form></Dialog></template>
