// Run from any cwd: node document/wireframes/fe/lesson-log/079-lesson-log/smoke.cjs
const {readFileSync}=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../../../..');
const {JSDOM,VirtualConsole}=require(require.resolve('jsdom',{paths:[path.join(root,'FE')]}));
const html=readFileSync(path.join(__dirname,'index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new Function(script);
let passed=0;
function setup(){const errors=[];const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e));const dom=new JSDOM(html,{runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')}}});const w=dom.window,d=w.document;const $=s=>d.querySelector(s);const change=(s,v)=>{$(s).value=v;$(s).dispatchEvent(new w.Event('change',{bubbles:true}))};const submit=s=>$(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));return{dom,w,d,$,change,submit,errors};}
function test(name,fn){const t=setup();try{fn(t);assert.equal(t.errors.length,0,t.errors.map(String).join('\n'));passed++;console.log('PASS',name)}finally{t.dom.window.close()}}
function complete(t){const values={'#titleInput':'Bài kiểm tra prototype','#gradeInput':'B','#progressInput':'ON_SCHEDULE','#presentInput':'39','#absentInput':'1'};for(const [s,v]of Object.entries(values))t.$(s).value=v}
function open(t,id){t.$(`#teacherCards [data-open="${id}"]`).click()}
test('grid 2 x 4 and seven days; no substitute or bulk approval controls',t=>{assert.equal(t.d.querySelectorAll('#matrixBody tr').length,8);assert.equal(t.d.querySelectorAll('#matrixHead th').length,8);assert.equal(t.$('#actualTeacherSelect'),null);assert.equal(t.$('#btnQuickReviewAll'),null)});
test('incomplete draft saves, incomplete submission stays in form',t=>{open(t,2);t.submit('#entryForm');assert.ok(t.$('#entryDialog').open);assert.match(t.$('#formError').textContent,/Vui lòng/);t.$('#saveDraft').click();assert.ok(!t.$('#entryDialog').open);assert.match(t.$('#teacherCards [data-open="2"]').parentElement.textContent,/Bản nháp/)});
test('one scheduled occurrence creates one entry and retains SUBMITTED on edit',t=>{open(t,3);complete(t);t.submit('#entryForm');open(t,3);assert.ok(t.$('#saveDraft').classList.contains('hidden'));t.$('#titleInput').value='Bài sửa';t.submit('#entryForm');assert.equal(t.d.querySelectorAll('#teacherCards [data-open="3"]').length,1);assert.match(t.$('#teacherCards [data-open="3"]').parentElement.textContent,/Đã nộp/)});
test('attendance validation rejects fractional and mismatched counts',t=>{open(t,2);complete(t);t.$('#presentInput').value='38.5';t.submit('#entryForm');assert.match(t.$('#formError').textContent,/số nguyên/);t.$('#presentInput').value='38';t.submit('#entryForm');assert.match(t.$('#formError').textContent,/bằng sĩ số/)});
test('expired draft locked for teacher, manager reason required for completion',t=>{t.change('#scenarioPicker','expired');open(t,2);assert.ok(t.$('#detailEdit').classList.contains('hidden'));t.$('[data-close="detailDialog"]').click();t.change('#rolePicker','office');t.$('#classPanel [data-open="2"]').click();t.$('#detailAmend').click();complete(t);t.submit('#entryForm');assert.match(t.$('#formError').textContent,/Lý do/);t.$('#reasonInput').value='Bổ sung sau hạn';t.submit('#entryForm');assert.match(t.$('#classPanel [data-open="2"]').textContent,/Đã điều chỉnh/)});
test('manager can record a missing overdue lesson',t=>{t.change('#scenarioPicker','expired');t.change('#rolePicker','admin');t.$('#classPanel [data-open="3"]').click();assert.match(t.$('#editorHeading').textContent,/Ghi bổ sung/);complete(t);t.$('#reasonInput').value='Bổ sung theo xác nhận giáo viên';t.submit('#entryForm');assert.match(t.$('#classPanel [data-open="3"]').textContent,/Đã điều chỉnh/)});
test('409 preserves typed input while inspecting latest server copy',t=>{t.change('#scenarioPicker','conflict');open(t,2);complete(t);t.submit('#entryForm');assert.equal(t.$('#titleInput').value,'Bài kiểm tra prototype');t.$('#loadLatest').click();assert.equal(t.$('#titleInput').value,'Bài kiểm tra prototype');assert.match(t.$('#latestPreview').textContent,/Bản mới nhất/);t.$('#useLatest').click();assert.match(t.$('#titleInput').value,/Bản mới nhất/);complete(t);t.submit('#entryForm');assert.ok(!t.$('#entryDialog').open)});
test('422 expiry keeps input but disables mutations',t=>{t.change('#scenarioPicker','expiry');open(t,2);complete(t);t.submit('#entryForm');assert.equal(t.$('#titleInput').value,'Bài kiểm tra prototype');assert.ok(t.$('#saveEntry').disabled);assert.ok(t.$('#saveDraft').disabled);assert.match(t.$('#formError').textContent,/422/)});
test('homeroom cannot review individual lessons; filters do not hide signing blockers',t=>{t.change('#rolePicker','homeroom');t.$('#classPanel [data-open="1"]').click();assert.ok(t.$('#detailReview').classList.contains('hidden'));assert.ok(t.$('#detailAmend').classList.contains('hidden'));t.$('[data-close="detailDialog"]').click();t.change('#statusFilter','SUBMITTED');assert.ok(t.$('#signWeek').disabled);assert.match(t.$('#weeklyBlock').textContent,/chưa kết thúc/)});
test('signed -> manager amend -> stale -> homeroom resign with reason; audit preserved',t=>{t.change('#scenarioPicker','signed');t.change('#rolePicker','office');t.$('#classPanel [data-open="1"]').click();t.$('#detailAmend').click();complete(t);t.$('#reasonInput').value='Sửa sĩ số';t.submit('#entryForm');assert.equal(t.$('#weeklyStatus').textContent,'Cần ký lại');t.change('#rolePicker','homeroom');t.$('#signWeek').click();t.submit('#weeklyForm');assert.match(t.$('#weeklyError').textContent,/lý do/);t.$('#resignReason').value='Đã đối chiếu bản điều chỉnh';t.submit('#weeklyForm');assert.equal(t.$('#weeklyStatus').textContent,'Đã ký');t.$('#weeklyHistory').click();assert.match(t.$('#auditBody').textContent,/INVALIDATE_WEEK/);assert.equal((t.$('#auditBody').textContent.match(/SIGN_WEEK/g)||[]).length,2)});
test('policy mode is exclusive and new policy preserves old lesson deadline',t=>{const old=t.$('#teacherCards').textContent;t.change('#rolePicker','office');t.$('#tabSettings').click();t.change('#deadlineMode','END_OF_WEEK');assert.ok(t.$('#hoursInput').disabled);t.$('#policyReason').value='Áp dụng quy định mới';t.submit('#policyForm');assert.match(t.$('#policyVersion').textContent,/mới nhất: 2/);t.change('#rolePicker','teacher');assert.equal(t.$('#teacherCards').textContent,old)});
test('archived source remains viewable; fallback states render without forms',t=>{t.change('#scenarioPicker','archived');open(t,2);assert.match(t.$('#editorNotice').textContent,/Đã lưu trữ/);for(const s of ['empty','forbidden','loading','network']){t.change('#scenarioPicker',s);assert.ok(t.$('#workspace').classList.contains('hidden'));assert.ok(t.$('#fallbackText').textContent);assert.equal(t.d.querySelectorAll('dialog[open]').length,0)}});
console.log(`JS syntax PASS; ${passed}/12 prototype scenarios PASS (JSDOM, not browser/live API).`);
