<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import Button from 'primevue/button'
import Select from 'primevue/select'
import DatePicker from 'primevue/datepicker'
import LessonLogWeeklyMatrix from '@/components/lesson-log/LessonLogWeeklyMatrix.vue'
import LessonLogEntryDialog from '@/components/lesson-log/LessonLogEntryDialog.vue'
import LessonLogStatusBadge from '@/components/lesson-log/LessonLogStatusBadge.vue'
import LessonLogDetailDialog from '@/components/lesson-log/LessonLogDetailDialog.vue'
import LessonLogAmendDialog from '@/components/lesson-log/LessonLogAmendDialog.vue'
import LessonLogAuditDrawer from '@/components/lesson-log/LessonLogAuditDrawer.vue'
import WeeklyHomeroomReviewDialog from '@/components/lesson-log/WeeklyHomeroomReviewDialog.vue'
import FormAlert from '@/components/common/FormAlert.vue'
import { amendLessonLog, createLessonLog, getClassWeeklyLessonLogs, listLessonLogClasses, reviewLessonLog, signWeeklyReview, submitLessonLog, updateLessonLog } from '@/services/lessonLogApi'
import { useAuthSession } from '@/composables/useAuthSession'
import { extractApiErrorMessage, isApiError } from '@/types/api'
import type { ClassWeekItem, ClassWeeklyLessonLogResponse, LessonGrade, LessonLogEntry, LessonLogRequestFields } from '@/types/lessonLog'

const { requireAccessToken } = useAuthSession(); const semesterId = ref(1); const classId = ref<number | null>(null); const weekStart = ref(new Date()); const classes = ref<Array<{ id: number; name: string }>>([]); const data = ref<ClassWeeklyLessonLogResponse | null>(null); const loading = ref(false); const saving = ref(false); const error = ref(''); const notice = ref(''); const statusFilter = ref<'ALL' | 'UNLOGGED' | LessonLogEntry['status']>('ALL'); const detailVisible = ref(false); const entryDialogVisible = ref(false); const amendVisible = ref(false); const auditVisible = ref(false); const reviewVisible = ref(false); const selected = ref<LessonLogEntry | null>(null); const editingNew = ref(false); const canManage = computed(() => Boolean(selected.value?.canReview || selected.value?.canAmend))
function iso(d: Date): string { return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
function monday(d: Date): Date { const x = new Date(d); const day = x.getDay() || 7; x.setDate(x.getDate() - day + 1); return x }
async function loadClasses(): Promise<void> { const token = requireAccessToken(); if (!token) return; try { classes.value = await listLessonLogClasses(semesterId.value, token); if (!classId.value && classes.value[0]) { classId.value = classes.value[0].id; await load() } } catch (e) { error.value = extractApiErrorMessage(e, 'Không thể tải danh sách lớp') } }
async function load(): Promise<void> { const token = requireAccessToken(); if (!token || !classId.value) return; loading.value = true; error.value = ''; try { data.value = await getClassWeeklyLessonLogs(classId.value, semesterId.value, iso(monday(weekStart.value)), token) } catch (e) { error.value = extractApiErrorMessage(e, 'Không thể tải sổ tuần của lớp') } finally { loading.value = false } }
function selectEntry(item: ClassWeekItem): void {
  selected.value = item
  if (item.status === 'UNLOGGED' && item.entryId <= 0) {
    editingNew.value = true
    entryDialogVisible.value = true
    return
  }
  editingNew.value = false
  detailVisible.value = true
}
function showAudit(entry: LessonLogEntry): void { selected.value = entry; detailVisible.value = false; auditVisible.value = true }
async function amend(fields: LessonLogRequestFields, reason: string): Promise<void> { const token = requireAccessToken(); if (!token || !selected.value) return; saving.value = true; error.value = ''; try { await amendLessonLog(selected.value.entryId, { expectedVersion: selected.value.version, reason, ...fields }, token); notice.value = 'Đã điều chỉnh sổ và lưu lý do vào lịch sử.'; amendVisible.value = false; await load() } catch (e) { error.value = isApiError(e, 409) ? 'Bản ghi đã thay đổi. Hãy mở lại chi tiết trước khi điều chỉnh.' : extractApiErrorMessage(e, 'Không thể điều chỉnh sổ') } finally { saving.value = false } }
async function review(): Promise<void> { const token = requireAccessToken(); if (!token || !selected.value) return; saving.value = true; error.value = ''; try { await reviewLessonLog(selected.value.entryId, selected.value.version, 'Duyệt sổ đầu bài', undefined, token); notice.value = 'Đã duyệt sổ đầu bài.'; detailVisible.value = false; await load() } catch (e) { error.value = isApiError(e, 409) ? 'Bản ghi đã thay đổi. Nội dung đang chọn được giữ nguyên; hãy tải lại để duyệt phiên bản mới.' : extractApiErrorMessage(e, 'Không thể duyệt sổ') } finally { saving.value = false } }
async function sign(comment: string, grade: LessonGrade | null, reason: string): Promise<void> { const token = requireAccessToken(); if (!token || !classId.value || !data.value?.weeklyReview) return; try { await signWeeklyReview(classId.value, { semesterId: semesterId.value, weekStart: data.value.weekStart, expectedVersion: data.value.weeklyReview.version, expectedEntries: data.value.weeklyReview.expectedEntries, weeklyComment: comment || undefined, weeklyGrade: grade ?? undefined, reason: reason || undefined }, token); notice.value = 'Đã ký tổng kết tuần.'; await load() } catch (e) { error.value = isApiError(e, 409) ? 'Tuần đã thay đổi. Bản nháp vẫn được giữ; hãy tải lại để ký theo phiên bản mới.' : extractApiErrorMessage(e, 'Không thể ký tổng kết tuần') } }
async function saveDraft(fields: LessonLogRequestFields): Promise<boolean> { const token = requireAccessToken(); if (!token || !selected.value) return false; saving.value = true; error.value = ''; try { if (editingNew.value) { selected.value = await createLessonLog({ timetableEntryId: selected.value.timetableEntryId, lessonDate: selected.value.lessonDate, ...fields }, token); editingNew.value = false } else selected.value = await updateLessonLog(selected.value.entryId, { expectedVersion: selected.value.version, ...fields }, token); notice.value = 'Đã lưu nháp.'; await load(); return true } catch (e) { error.value = isApiError(e, 409) ? 'Dữ liệu đã thay đổi. Hãy tải lại sổ tuần trước khi ghi tiếp.' : extractApiErrorMessage(e, 'Không thể lưu sổ đầu bài'); return false } finally { saving.value = false } }
async function submit(fields: LessonLogRequestFields): Promise<void> { const saved = await saveDraft(fields); if (!saved || !selected.value?.entryId) return; const token = requireAccessToken(); if (!token) return; saving.value = true; try { selected.value = await submitLessonLog(selected.value.entryId, selected.value.version, token); notice.value = 'Đã nộp sổ đầu bài.'; await load() } catch (e) { error.value = isApiError(e, 409) ? 'Đã lưu nội dung nhưng phiên bản đã thay đổi; sổ chưa được nộp.' : `Đã lưu nháp, chưa nộp. ${extractApiErrorMessage(e, 'Vui lòng kiểm tra lại')}` } finally { saving.value = false } }
const filteredEntries = computed(() => { if (!data.value || statusFilter.value === 'ALL') return data.value?.items ?? []; return data.value.items.filter((entry) => entry.status === statusFilter.value) }); onMounted(() => void loadClasses())
</script>
<template>
  <div class="lesson-page"><header class="page-heading"><div><p class="eyebrow">SỔ ĐẦU BÀI</p><h1>Sổ tuần theo lớp</h1><p>Tuần bắt đầu từ thứ Hai; dữ liệu lịch nghỉ và điều kiện ký do máy chủ trả về.</p></div><div class="toolbar"><Select v-model="classId" :options="classes" option-label="name" option-value="id" placeholder="Chọn lớp" aria-label="Lớp" @change="load" /><DatePicker v-model="weekStart" date-format="dd/mm/yy" show-icon aria-label="Tuần" @update:model-value="load" /></div></header><FormAlert v-if="error" tone="error" :message="error" /><FormAlert v-if="notice" tone="success" :message="notice" /><div v-if="loading" class="state">Đang tải sổ tuần…</div><template v-else-if="data"><div class="summary-grid"><div><strong>{{ data.summary.scheduled }}</strong><span>Tiết dự kiến</span></div><div><strong>{{ data.summary.unlogged }}</strong><span>Chưa ghi</span></div><div><strong>{{ data.summary.draft }}</strong><span>Nháp</span></div><div><strong>{{ data.summary.submitted + data.summary.reviewed + data.summary.amended }}</strong><span>Đã nộp trở lên</span></div></div><div v-if="data.weeklyReview" class="review-bar"><div><LessonLogStatusBadge :status="data.weeklyReview.status" /><span v-if="data.weeklyReview.signedBy"> {{ data.weeklyReview.signedBy }} · {{ data.weeklyReview.signedAt }}</span><ul v-if="data.weeklyReview.blockedReasons.length"><li v-for="reason in data.weeklyReview.blockedReasons" :key="reason">{{ reason }}</li></ul></div><Button label="Ký tổng kết tuần" icon="pi pi-check" :disabled="!data.weeklyReview.canSignWeek" @click="reviewVisible = true" /></div><div class="toolbar filter"><label for="lesson-status-filter">Hiển thị</label><Select id="lesson-status-filter" v-model="statusFilter" :options="[{ label: 'Tất cả', value: 'ALL' }, { label: 'Chưa ghi', value: 'UNLOGGED' }, { label: 'Nháp', value: 'DRAFT' }, { label: 'Đã nộp', value: 'SUBMITTED' }, { label: 'Đã duyệt', value: 'REVIEWED' }, { label: 'Đã điều chỉnh', value: 'AMENDED' }]" option-label="label" option-value="value" /><span v-if="statusFilter !== 'ALL'">{{ filteredEntries.length }} bản ghi phù hợp</span></div><LessonLogWeeklyMatrix :days="data.calendarDays" :entries="filteredEntries" @select="selectEntry" /></template><div v-else class="state">Chưa có dữ liệu sổ tuần.</div><LessonLogEntryDialog v-model:visible="entryDialogVisible" :entry="selected" :read-only="Boolean(selected && !selected.canTeacherEdit)" :saving="saving" :error-message="error" @save-draft="saveDraft" @submit="submit" /><LessonLogDetailDialog v-model:visible="detailVisible" :entry="selected" @audit="showAudit" /><LessonLogAmendDialog v-if="canManage" v-model:visible="amendVisible" :entry="selected" :saving="saving" @amend="amend" /><LessonLogAuditDrawer v-model:visible="auditVisible" :entry="selected" /><WeeklyHomeroomReviewDialog v-if="data?.weeklyReview" v-model:visible="reviewVisible" :review="data.weeklyReview" @sign="sign" /></div>
  <div v-if="selected && canManage" class="selected-actions"><Button v-if="selected.canReview" label="Duyệt bản đang chọn" icon="pi pi-check" :loading="saving" @click="review" /><Button v-if="selected.canAmend" label="Điều chỉnh bản đang chọn" icon="pi pi-pencil" severity="warn" @click="amendVisible = true" /></div>
</template>
<style scoped>.lesson-page{max-width:1250px;margin:auto;padding:28px;display:grid;gap:20px}.page-heading{display:flex;justify-content:space-between;gap:16px}.toolbar{display:flex;gap:10px;align-items:center}.summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.summary-grid div{padding:16px;background:#fff;border:1px solid #dbe3ec;border-radius:10px}.summary-grid strong,.summary-grid span{display:block}.summary-grid strong{font-size:24px}.summary-grid span{color:#64748b;font-size:13px}.review-bar{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;padding:16px;background:#fff;border:1px solid #dbe3ec;border-radius:10px}.review-bar ul{margin:8px 0 0;padding-left:18px;color:#9a3412;font-size:13px}.filter{justify-content:flex-end}.filter span{font-size:13px;color:#64748b}.state{padding:32px;text-align:center;background:#fff;border-radius:12px;color:#64748b}@media(max-width:760px){.page-heading,.review-bar{flex-direction:column}.toolbar{flex-wrap:wrap}.summary-grid{grid-template-columns:repeat(2,1fr)}}</style>
