<script setup lang="ts">
import LessonLogSubtabs from '@/components/lesson-log/LessonLogSubtabs.vue'
import { onMounted, ref } from 'vue'; import Button from 'primevue/button'; import InputNumber from 'primevue/inputnumber'; import InputText from 'primevue/inputtext'; import Select from 'primevue/select'; import FormAlert from '@/components/common/FormAlert.vue'; import { getLessonLogPolicy, updateLessonLogPolicy } from '@/services/lessonLogApi'; import { useAuthSession } from '@/composables/useAuthSession'; import { extractApiErrorMessage } from '@/types/api'; import type { DeadlineMode, LessonLogPolicy } from '@/types/lessonLog';
const { requireAccessToken }=useAuthSession(); const policy=ref<LessonLogPolicy|null>(null); const mode=ref<DeadlineMode>('FIXED_HOURS'); const hours=ref<number|null>(48); const effectiveFrom=ref(''); const timezone=ref('Asia/Ho_Chi_Minh'); const requireReview=ref(true); const reason=ref(''); const loading=ref(true); const saving=ref(false); const error=ref(''); const notice=ref(''); const modes=[{label:'Số giờ từ khi kết thúc tiết',value:'FIXED_HOURS'},{label:'Đến hết tuần',value:'END_OF_WEEK'}]
function hcmToday():string{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(value=>value.type===type)?.value??'';return `${part('year')}-${part('month')}-${part('day')}`}
function nextEffectiveFrom(latestEffectiveFrom:string):string{const today=hcmToday();const latestDate=latestEffectiveFrom>today?latestEffectiveFrom:today;const [year,month,day]=latestDate.split('-').map(Number);const nextDate=new Date(Date.UTC(year,month-1,day+1));return `${nextDate.getUTCFullYear()}-${String(nextDate.getUTCMonth()+1).padStart(2,'0')}-${String(nextDate.getUTCDate()).padStart(2,'0')}`}
async function load(){const token=requireAccessToken();if(!token)return;try{policy.value=await getLessonLogPolicy(undefined,token); mode.value=policy.value.deadlineMode;hours.value=policy.value.editWindowHours;effectiveFrom.value=nextEffectiveFrom(policy.value.effectiveFrom);timezone.value=policy.value.timezone;requireReview.value=policy.value.requireHomeroomReview}catch(e){error.value=extractApiErrorMessage(e,'Không thể tải chính sách')}finally{loading.value=false}}
async function save(){const token=requireAccessToken();if(!token||!policy.value)return;if(!reason.value.trim()){error.value='Lý do thay đổi là bắt buộc.';notice.value='';return}saving.value=true;error.value='';try{policy.value=await updateLessonLogPolicy({expectedVersion:policy.value.version,effectiveFrom:effectiveFrom.value,timezone:timezone.value,deadlineMode:mode.value,editWindowHours:mode.value==='FIXED_HOURS'?hours.value:null,requireHomeroomReview:requireReview.value,rubric:policy.value.rubric,reason:reason.value.trim()},token);effectiveFrom.value=nextEffectiveFrom(policy.value.effectiveFrom);notice.value='Đã tạo phiên bản chính sách mới.';reason.value=''}catch(e){error.value=extractApiErrorMessage(e,'Không thể lưu chính sách')}finally{saving.value=false}}
onMounted(()=>void load())
</script>
<template><div class="lesson-page"><LessonLogSubtabs show-policy /><div class="page-heading"><div><h1>Chính sách sổ đầu bài</h1></div></div><FormAlert v-if="error" tone="error" :message="error" /><FormAlert v-if="notice" tone="success" :message="notice" /><div v-if="loading" class="lesson-loading">Đang tải chính sách…</div><form v-else-if="policy" class="settings-card" @submit.prevent="save"><label>Kiểu hạn sửa<Select v-model="mode" :options="modes" option-label="label" option-value="value" /></label><label v-if="mode==='FIXED_HOURS'">Số giờ<InputNumber v-model="hours" :min="1" :max="168" /></label><label>Ngày hiệu lực<InputText v-model="effectiveFrom" type="date" /></label><label>Múi giờ<InputText v-model="timezone" readonly /></label><label class="checkbox"><input v-model="requireReview" type="checkbox"> Bắt buộc GVCN ký tổng kết tuần</label><label>Lý do thay đổi <span class="required-mark" aria-hidden="true">*</span><InputText v-model="reason" required aria-required="true" maxlength="500" placeholder="Bắt buộc khi tạo phiên bản" /></label><Button type="submit" label="Tạo phiên bản mới" icon="pi pi-save" :loading="saving" :disabled="!reason.trim()" /></form></div></template><style scoped>.lesson-page{max-width:820px;margin:auto;padding:28px;display:grid;gap:20px}.settings-card{display:grid;gap:16px;padding:22px;background:#fff;border:1px solid #dbe3ec;border-radius:12px}.settings-card label{display:grid;gap:7px;font-weight:600}.required-mark{color:var(--error,#ba1a1a)}.checkbox{display:flex!important;align-items:center;gap:8px}</style>
