<script setup lang="ts">
import LessonLogSubtabs from '@/components/lesson-log/LessonLogSubtabs.vue'
import { onMounted, ref } from 'vue'; import Button from 'primevue/button'; import InputNumber from 'primevue/inputnumber'; import InputText from 'primevue/inputtext'; import Select from 'primevue/select'; import FormAlert from '@/components/common/FormAlert.vue'; import { getLessonLogPolicy, updateLessonLogPolicy } from '@/services/lessonLogApi'; import { useAuthSession } from '@/composables/useAuthSession'; import { extractApiErrorMessage } from '@/types/api'; import type { DeadlineMode, LessonLogPolicy } from '@/types/lessonLog';
const { requireAccessToken }=useAuthSession(); const policy=ref<LessonLogPolicy|null>(null); const mode=ref<DeadlineMode>('FIXED_HOURS'); const hours=ref<number|null>(48); const effectiveFrom=ref(''); const timezone=ref('Asia/Ho_Chi_Minh'); const requireReview=ref(true); const reason=ref(''); const loading=ref(true); const saving=ref(false); const error=ref(''); const notice=ref(''); const modes=[{label:'Số giờ từ khi kết thúc tiết',value:'FIXED_HOURS'},{label:'Đến hết tuần',value:'END_OF_WEEK'}]
async function load(){const token=requireAccessToken();if(!token)return;try{policy.value=await getLessonLogPolicy(undefined,token); mode.value=policy.value.deadlineMode;hours.value=policy.value.editWindowHours;effectiveFrom.value=policy.value.effectiveFrom;timezone.value=policy.value.timezone;requireReview.value=policy.value.requireHomeroomReview}catch(e){error.value=extractApiErrorMessage(e,'Không thể tải chính sách')}finally{loading.value=false}}
async function save(){const token=requireAccessToken();if(!token||!policy.value)return;if(!reason.value.trim()){error.value='Lý do thay đổi là bắt buộc.';notice.value='';return}saving.value=true;error.value='';try{policy.value=await updateLessonLogPolicy({expectedVersion:policy.value.version,effectiveFrom:effectiveFrom.value,timezone:timezone.value,deadlineMode:mode.value,editWindowHours:mode.value==='FIXED_HOURS'?hours.value:null,requireHomeroomReview:requireReview.value,rubric:policy.value.rubric,reason:reason.value.trim()},token);notice.value='Đã tạo phiên bản chính sách mới.';reason.value=''}catch(e){error.value=extractApiErrorMessage(e,'Không thể lưu chính sách')}finally{saving.value=false}}
onMounted(()=>void load())
</script>
<template><div class="lesson-page"><LessonLogSubtabs show-policy /><div class="page-heading"><div><h1>Chính sách sổ đầu bài</h1></div></div><FormAlert v-if="error" tone="error" :message="error" /><FormAlert v-if="notice" tone="success" :message="notice" /><div v-if="loading" class="lesson-loading">Đang tải chính sách…</div><form v-else-if="policy" class="settings-card" @submit.prevent="save"><label>Kiểu hạn sửa<Select v-model="mode" :options="modes" option-label="label" option-value="value" /></label><label v-if="mode==='FIXED_HOURS'">Số giờ<InputNumber v-model="hours" :min="1" :max="168" /></label><label>Ngày hiệu lực<InputText v-model="effectiveFrom" type="date" /></label><label>Múi giờ<InputText v-model="timezone" readonly /></label><label class="checkbox"><input v-model="requireReview" type="checkbox"> Bắt buộc GVCN ký tổng kết tuần</label><label>Lý do thay đổi <span class="required-mark" aria-hidden="true">*</span><InputText v-model="reason" required aria-required="true" maxlength="500" placeholder="Bắt buộc khi tạo phiên bản" /></label><div class="rubric"><h2>Rubric hiện hành</h2><div v-for="item in policy.rubric" :key="item.code"><strong>{{ item.code }} · {{ item.label }}</strong><span>{{ item.description }}</span></div></div><Button type="submit" label="Tạo phiên bản mới" icon="pi pi-save" :loading="saving" :disabled="!reason.trim()" /></form></div></template><style scoped>.lesson-page{max-width:820px;margin:auto;padding:28px;display:grid;gap:20px}.settings-card{display:grid;gap:16px;padding:22px;background:#fff;border:1px solid #dbe3ec;border-radius:12px}.settings-card label{display:grid;gap:7px;font-weight:600}.required-mark{color:var(--error,#ba1a1a)}.checkbox{display:flex!important;align-items:center;gap:8px}.rubric{padding-top:10px;border-top:1px solid #e2e8f0}.rubric h2{font-size:16px}.rubric div{display:grid;gap:3px;padding:8px 0}.rubric span{color:#64748b;font-weight:400}</style>
