<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import Button from 'primevue/button'
import FormAlert from '@/components/FormAlert.vue'
import PageState from '@/components/PageState.vue'
import AssignmentContextPanel from '@/components/AssignmentContextPanel.vue'
import HomeroomAssignmentCard from '@/components/HomeroomAssignmentCard.vue'
import HomeroomHistoryDialog from '@/components/HomeroomHistoryDialog.vue'
import ClassSubjectAssignmentTable from '@/components/ClassSubjectAssignmentTable.vue'
import TeacherAssignmentScheduleTable from '@/components/TeacherAssignmentScheduleTable.vue'
import HomeroomAssignmentDialog from '@/components/HomeroomAssignmentDialog.vue'
import SubjectAssignmentDialog from '@/components/SubjectAssignmentDialog.vue'
import Select from 'primevue/select'
import { useRouter } from 'vue-router'
import { clearAuthSession, getAuthSession } from '@/services/authSession'
import { fetchAcademicYears, fetchClassSubjects, fetchGrades, fetchSchoolClasses, fetchSemesters } from '@/services/academicApi'
import { createHomeroomAssignment, createSubjectTeachingAssignment, endHomeroomAssignment, endSubjectTeachingAssignment, fetchHomeroomAssignmentsByClass, fetchHomeroomAssignmentsByTeacher, fetchSubjectAssignmentsByClass, fetchSubjectAssignmentsByTeacher, replaceHomeroomAssignment, replaceSubjectTeachingAssignment } from '@/services/assignmentApi'
import { fetchTeachers } from '@/services/teacherApi'
import { isApiError } from '@/types/api'
import type { AcademicYear, ClassSubject, GradeLevel, SchoolClass, Semester, Subject } from '@/types/academic'
import type { AssignmentFormValues, HomeroomAssignment, SubjectTeachingAssignment } from '@/types/assignment'
import type { Teacher } from '@/types/teacher'
import type { LoadingState } from '@/types/ui'
const router = useRouter(); const tab = ref<'class' | 'teacher'>('class'); const academicYears = ref<AcademicYear[]>([]); const grades = ref<GradeLevel[]>([]); const classes = ref<SchoolClass[]>([]); const semesters = ref<Semester[]>([]); const teachers = ref<Teacher[]>([]); const classSubjects = ref<ClassSubject[]>([]); const subjects = ref<Subject[]>([]); const homerooms = ref<HomeroomAssignment[]>([]); const subjectAssignments = ref<SubjectTeachingAssignment[]>([]); const teacherOwnHomerooms = ref<HomeroomAssignment[]>([]); const teacherOwnSubjectAssignments = ref<SubjectTeachingAssignment[]>([]); const selectedAcademicYearId = ref<number | null>(null); const selectedGradeId = ref<number | null>(null); const selectedClassId = ref<number | null>(null); const selectedSemesterId = ref<number | null>(null); const selectedTeacherId = ref<number | null>(null); const state = ref<LoadingState>('loading'); const errorMessage = ref(''); const forbidden = ref(false); const mutationError = ref(''); const statusMessage = ref(''); const saving = ref(false); const homeroomDialogVisible = ref(false); const homeroomMode = ref<'create' | 'replace' | 'end'>('create'); const selectedHomeroom = ref<HomeroomAssignment | null>(null); const subjectDialogVisible = ref(false); const subjectMode = ref<'create' | 'replace' | 'end'>('create'); const selectedSubjectAssignment = ref<SubjectTeachingAssignment | null>(null); const historyVisible = ref(false); const teacherSchedule = ref<SubjectTeachingAssignment[]>([]); const scheduleLoading = ref(false)
function normalizedRoles(): string[] { return (getAuthSession()?.user.roles ?? []).map((role) => role.replace(/^ROLE_/i, '').toUpperCase()) }
const selectedClass = computed(() => classes.value.find((x) => x.id === selectedClassId.value) ?? null); const filteredClasses = computed(() => selectedGradeId.value === null ? classes.value : classes.value.filter((x) => x.gradeLevelId === selectedGradeId.value)); const filteredGrades = computed(() => teacherReadOnly.value ? grades.value.filter((grade) => classes.value.some((schoolClass) => schoolClass.gradeLevelId === grade.id)) : grades.value); const officeUser = computed(() => { const roles = normalizedRoles(); return roles.includes('ADMIN') || roles.includes('ACADEMIC_OFFICE') }); const teacherReadOnly = computed(() => !officeUser.value && normalizedRoles().includes('TEACHER')); const classReadOnly = computed(() => teacherReadOnly.value || selectedClass.value?.status === 'CLOSED'); const activeHomeroom = computed(() => homerooms.value.find((x) => x.status === 'ACTIVE') ?? null); const teacherHasAssignment = computed(() => teacherReadOnly.value ? teacherOwnHomerooms.value.some((item) => item.status === 'ACTIVE') || teacherOwnSubjectAssignments.value.some((item) => item.status === 'ACTIVE') : homerooms.value.some((item) => item.status === 'ACTIVE') || subjectAssignments.value.some((item) => item.status === 'ACTIVE'))
function token(): string | null { const session = getAuthSession(); if (session) return session.accessToken; clearAuthSession(); void router.replace({ name: 'login' }); return null }
function message(error: unknown, fallback: string): string { return error instanceof Error && error.message ? error.message : fallback }
async function loadInitial(): Promise<void> { const t = token(); if (!t) return; try { const teacherList = await fetchTeachers(t); teachers.value = teacherList; if (teacherReadOnly.value) { selectedTeacherId.value = teacherList.find((teacher) => teacher.userId === getAuthSession()?.user.id)?.id ?? null; if (selectedTeacherId.value === null) throw new Error('Tài khoản chưa có hồ sơ giáo viên liên kết.'); const years = await fetchAcademicYears(t); const yearId = years.find((x) => x.status === 'ACTIVE')?.id ?? years[0]?.id ?? null; const [gradeList, classList, semesterList, ownSubjectAssignments, ownHomerooms] = await Promise.all([fetchGrades(t), fetchSchoolClasses(t, yearId ?? undefined), yearId === null ? Promise.resolve([] as Semester[]) : fetchSemesters(t, yearId), fetchSubjectAssignmentsByTeacher(t, selectedTeacherId.value), fetchHomeroomAssignmentsByTeacher(t, selectedTeacherId.value)]); academicYears.value = years; grades.value = gradeList; selectedAcademicYearId.value = yearId; const activeHomerooms = ownHomerooms.filter((assignment) => assignment.status === 'ACTIVE'); const activeSubjectAssignments = ownSubjectAssignments.filter((assignment) => assignment.status === 'ACTIVE'); classes.value = classList.filter((item) => activeHomerooms.some((assignment) => assignment.classId === item.id) || activeSubjectAssignments.some((assignment) => assignment.classId === item.id)); semesters.value = semesterList; teacherOwnSubjectAssignments.value = ownSubjectAssignments; teacherOwnHomerooms.value = ownHomerooms; subjectAssignments.value = ownSubjectAssignments; homerooms.value = ownHomerooms; tab.value = teacherHasAssignment.value ? 'class' : 'teacher'; selectedClassId.value = classes.value[0]?.id ?? null; selectedGradeId.value = classes.value.find((item) => item.id === selectedClassId.value)?.gradeLevelId ?? null; selectedSemesterId.value = semesterList.find((x) => x.status === 'ACTIVE')?.id ?? semesterList[0]?.id ?? null; return } const [years, gradeLevels] = await Promise.all([fetchAcademicYears(t), fetchGrades(t)]); academicYears.value = years; grades.value = gradeLevels; selectedAcademicYearId.value = years.find((x) => x.status === 'ACTIVE')?.id ?? years[0]?.id ?? null; selectedTeacherId.value = Number(router.currentRoute.value.query.teacherId) || teacherList[0]?.id || null; await loadYear() } catch (error) { if (isApiError(error, 401)) return; forbidden.value = isApiError(error, 403); errorMessage.value = message(error, 'Không thể tải context phân công.'); state.value = 'error' } }
async function loadYear(): Promise<void> { const t = token(); if (!t || selectedAcademicYearId.value === null) return; try { const [classList, semesterList] = await Promise.all([fetchSchoolClasses(t, selectedAcademicYearId.value), fetchSemesters(t, selectedAcademicYearId.value)]); const permittedClassIds = new Set([...teacherOwnHomerooms.value.map((item) => item.classId), ...teacherOwnSubjectAssignments.value.map((item) => item.classId)].filter((id): id is number => id !== null && id !== undefined)); classes.value = teacherReadOnly.value ? classList.filter((item) => permittedClassIds.has(item.id)) : classList; semesters.value = semesterList; selectedGradeId.value = classes.value[0]?.gradeLevelId ?? grades.value[0]?.id ?? null; selectedClassId.value = classes.value[0]?.id ?? null; selectedSemesterId.value = semesterList.find((x) => x.status === 'ACTIVE')?.id ?? semesterList[0]?.id ?? null } catch (error) { if (isApiError(error, 401)) return; errorMessage.value = message(error, 'Không thể tải lớp và học kỳ.'); state.value = 'error' } }
async function loadClass(): Promise<void> { const t = token(); if (!t || selectedClassId.value === null) return; if (teacherReadOnly.value && !classes.value.some((item) => item.id === selectedClassId.value)) { forbidden.value = true; errorMessage.value = 'Bạn chỉ được xem các lớp có phân công của mình.'; state.value = 'error'; return } state.value = 'loading'; try { const [h, cs, assignments] = await Promise.all([fetchHomeroomAssignmentsByClass(t, selectedClassId.value), selectedSemesterId.value === null ? Promise.resolve([] as ClassSubject[]) : fetchClassSubjects(t, selectedClassId.value, selectedSemesterId.value), selectedSemesterId.value === null ? Promise.resolve([] as SubjectTeachingAssignment[]) : fetchSubjectAssignmentsByClass(t, selectedClassId.value, selectedSemesterId.value)]); homerooms.value = h; classSubjects.value = cs; subjectAssignments.value = assignments; state.value = 'success'; await loadSubjects() } catch (error) { if (isApiError(error, 401)) return; forbidden.value = isApiError(error, 403); errorMessage.value = message(error, 'Không thể tải phân công của lớp.'); state.value = 'error' } }
async function loadSubjects(): Promise<void> { const t = token(); if (!t) return; try { const { fetchSubjects } = await import('@/services/academicApi'); subjects.value = await fetchSubjects(t) } catch { subjects.value = [] } }
async function loadSchedule(): Promise<void> { const t = token(); if (!t || selectedTeacherId.value === null) return; scheduleLoading.value = true; try { teacherSchedule.value = await fetchSubjectAssignmentsByTeacher(t, selectedTeacherId.value) } catch (error) { if (isApiError(error, 401)) return; errorMessage.value = message(error, 'Không thể tải lịch giảng dạy theo giáo viên.') } finally { scheduleLoading.value = false } }
function openHomeroom(mode: 'create' | 'replace' | 'end', assignment: HomeroomAssignment | null = null): void { homeroomMode.value = mode; selectedHomeroom.value = assignment; mutationError.value = ''; homeroomDialogVisible.value = true }
function openSubject(mode: 'create' | 'replace' | 'end', assignment: SubjectTeachingAssignment | null = null): void { subjectMode.value = mode; selectedSubjectAssignment.value = assignment; mutationError.value = ''; subjectDialogVisible.value = true }
async function saveHomeroom(values: AssignmentFormValues): Promise<void> { const t = token(); if (!t || selectedClassId.value === null) return; saving.value = true; mutationError.value = ''; try { const body = { teacherId: values.teacherId!, validFrom: values.validFrom, validTo: values.validTo || null }; if (homeroomMode.value === 'create') await createHomeroomAssignment(t, selectedClassId.value, body); else if (selectedHomeroom.value && homeroomMode.value === 'replace') await replaceHomeroomAssignment(t, selectedHomeroom.value.id, body); else if (selectedHomeroom.value) await endHomeroomAssignment(t, selectedHomeroom.value.id, { validTo: values.validTo }); statusMessage.value = 'Đã cập nhật phân công GVCN.'; homeroomDialogVisible.value = false; await loadClass() } catch (error) { if (isApiError(error, 401)) return; mutationError.value = message(error, 'Không thể cập nhật phân công GVCN.') } finally { saving.value = false } }
async function saveSubject(values: AssignmentFormValues): Promise<void> { const t = token(); if (!t || !selectedSubjectAssignment.value && subjectMode.value !== 'create') return; const classSubjectId = (selectedSubjectAssignment.value?.classSubjectId ?? selectedClassSubjectId.value); if (!classSubjectId) return; saving.value = true; mutationError.value = ''; try { const body = { teacherId: values.teacherId!, validFrom: values.validFrom, validTo: values.validTo || null }; if (subjectMode.value === 'create') await createSubjectTeachingAssignment(t, classSubjectId, body); else if (selectedSubjectAssignment.value && subjectMode.value === 'replace') await replaceSubjectTeachingAssignment(t, selectedSubjectAssignment.value.id, body); else if (selectedSubjectAssignment.value) await endSubjectTeachingAssignment(t, selectedSubjectAssignment.value.id, { validTo: values.validTo }); statusMessage.value = 'Đã cập nhật phân công GVBM.'; subjectDialogVisible.value = false; await loadClass() } catch (error) { if (isApiError(error, 401)) return; mutationError.value = message(error, 'Không thể cập nhật phân công GVBM.') } finally { saving.value = false } }
const selectedClassSubjectId = ref<number | null>(null); function assignSubject(item: ClassSubject): void { selectedClassSubjectId.value = item.id; openSubject('create') }
watch(selectedAcademicYearId, (v, old) => { if (v !== old) void loadYear() }); watch(selectedGradeId, (v, old) => { if (v !== old) selectedClassId.value = filteredClasses.value[0]?.id ?? null }); watch([selectedClassId, selectedSemesterId], ([c, s], [oc, os]) => { if (c !== oc || s !== os) void loadClass() }); watch([tab, selectedTeacherId], ([t, id], [ot, oid]) => { if (t === 'teacher' && (t !== ot || id !== oid)) void loadSchedule() }); onMounted(() => { void loadInitial() })
</script>
<template><div class="page-content"><header class="page-heading"><div><p class="eyebrow">Quản lý giảng dạy</p><h1>Phân công giảng dạy</h1><p>{{ teacherReadOnly ? 'Xem các phân công giảng dạy của bạn.' : 'Quản lý GVCN, GVBM theo lớp và lịch dạy theo giáo viên.' }}</p></div></header><FormAlert v-if="statusMessage" tone="success" :message="statusMessage" /><FormAlert v-if="mutationError" tone="error" :message="mutationError" /><div class="tab-strip"><Button v-if="!teacherReadOnly || teacherHasAssignment" label="Phân công theo lớp" icon="pi pi-building" :severity="tab === 'class' ? 'primary' : 'secondary'" :outlined="tab !== 'class'" @click="tab = 'class'" /><Button :label="teacherReadOnly ? 'Phân công của tôi' : 'Phân công theo GV'" icon="pi pi-calendar" :severity="tab === 'teacher' ? 'primary' : 'secondary'" :outlined="tab !== 'teacher'" @click="tab = 'teacher'" /></div><AssignmentContextPanel v-if="tab === 'class'" v-model:academic-year-id="selectedAcademicYearId" v-model:grade-id="selectedGradeId" v-model:class-id="selectedClassId" v-model:semester-id="selectedSemesterId" :academic-years="academicYears" :grades="filteredGrades" :classes="filteredClasses" :semesters="semesters" /><div v-if="tab === 'class'"><PageState :state="state" :error-message="errorMessage" :forbidden="forbidden" @retry="loadClass"><template #default><HomeroomAssignmentCard :assignment="activeHomeroom" :teachers="teachers" :read-only="classReadOnly" @assign="openHomeroom('create')" @replace="openHomeroom('replace', $event)" @end="openHomeroom('end', $event)" @history="historyVisible = true" /><ClassSubjectAssignmentTable :class-subjects="classSubjects" :subjects="subjects" :assignments="subjectAssignments" :teachers="teachers" :read-only="classReadOnly" @assign="assignSubject" @replace="openSubject('replace', $event)" @end="openSubject('end', $event)" /></template></PageState></div><div v-else class="content-surface"><div v-if="!teacherReadOnly" class="field-group schedule-selector"><label for="schedule-teacher">Chọn giáo viên</label><Select id="schedule-teacher" v-model="selectedTeacherId" :options="teachers" option-label="teacherName" option-value="id" placeholder="Chọn giáo viên" fluid /></div><TeacherAssignmentScheduleTable :assignments="teacherSchedule" :classes="classes" :class-subjects="classSubjects" :subjects="subjects" :loading="scheduleLoading" /></div><HomeroomHistoryDialog v-model:visible="historyVisible" :assignments="homerooms" :teachers="teachers" /><HomeroomAssignmentDialog v-model:visible="homeroomDialogVisible" :mode="homeroomMode" :assignment="selectedHomeroom" :teachers="teachers" :saving="saving" :error-message="mutationError" @save="saveHomeroom" /><SubjectAssignmentDialog v-model:visible="subjectDialogVisible" :mode="subjectMode" :assignment="selectedSubjectAssignment" :teachers="teachers" :saving="saving" :error-message="mutationError" @save="saveSubject" /></div></template>
